create DATABASE EMPRESA;

USE EMPRESA;

CREATE TABLE EMPRESA(

ID_EMPRESA INT auto_increment,
NOME_EMPRESA VARCHAR(45),
CEO_EMPRESA VARCHAR(45),

PRIMARY KEY (ID_EMPRESA)

);

CREATE TABLE DEPARTAMENTO(

ID_DEPARTAMENTO INT AUTO_INCREMENT,
NOME_DEPARTAMENTO VARCHAR(45),
NUMERO_DEPARTAMENTO INT,

PRIMARY KEY (ID_DEPARTAMENTO)

);

CREATE TABLE DEPARTAMENTO_HAS_EMPRESA(

FK_DEPARTAMENTO INT,
FK_EMPRESA INT,

FOREIGN KEY (FK_DEPARTAMENTO) REFERENCES DEPARTAMENTO(ID_DEPARTAMENTO),
FOREIGN KEY (FK_EMPRESA) REFERENCES EMPRESA(ID_EMPRESA)

);

CREATE TABLE FUNCIONARIO(

ID_FUNCIONARIO INT AUTO_INCREMENT,
NOME_FUNCIONARIO VARCHAR(45),
SOBRENOME_FUNCIONARIO VARCHAR(45),
TITULO_FUNCIONARIO VARCHAR(45),
SALARIO decimal(6,2),
FK_DEPARTAMENTO INT,
FK_CHEFE INT,

PRIMARY KEY (ID_FUNCIONARIO),
FOREIGN KEY (FK_DEPARTAMENTO) REFERENCES DEPARTAMENTO(ID_DEPARTAMENTO),
FOREIGN KEY (FK_CHEFE) REFERENCES FUNCIONARIO(ID_FUNCIONARIO)

)auto_increment = 100;

INSERT INTO EMPRESA VALUES	(NULL, 'SANSUNG', 'Kim Hyun-suk'), (NULL, 'MOTOROLA', 'Greg Brown'), (NULL, 'NOKIA', 'Pekka Lundmark'),
							(NULL, 'APPLE', 'Tim Cook');
                            
INSERT INTO DEPARTAMENTO VALUES	(NULL, 'INOVAÇÃO', 110), (NULL, 'MARKETING', 120), (NULL, 'PROCESSOS', 130), (NULL, 'PLANEJAMENTO FINANCEIRO', 140),
								(NULL, 'ADMINISTRATIVO', 150);
                                
INSERT INTO DEPARTAMENTO_HAS_EMPRESA VALUES	('1', '4'), ('1', '1'), ('2', '2'), ('2', '4'), ('3', '3'), ('4', '1'), ('4', '3'),
											('5', '3'), ('5', '2');
                                            
INSERT INTO FUNCIONARIO VALUES 	(NULL, 'DANIEL', 'KATSUAKI', 'ESTAGIARIO', 1500.00 ,'1', NULL), (NULL, 'SAMUEL', 'TAMOAKI', 'EFETIVADO', 1100.00, '4', NULL),
								(NULL, 'VITOR', 'HERCULANO', 'ESTAGIARIO', 1400.00, '1', NULL), (NULL, 'KENNEDY', 'FIORENTINO', 'ESTAGIARIO', 1800.00, '2', NULL),
								(NULL, 'LUCAS', 'DA SILVA', 'EFETIVADO', 1300.00, 3, NULL), (NULL, 'SISSY', 'LINO', 'EFETIVADA', 1600.00, '5', NULL),
                                (NULL, 'KATYE', 'ESAKA', 'EFETIVADA', 1200.00, '3', NULL);
                                
INSERT INTO FUNCIONARIO VALUES (NULL, 'GUILHERME', 'PINHEIRO', 'EFETIVADO', 2500.00, '1', NULL), (NULL, 'ANA', 'LUIZA', 'EFETIVADA', 2200.00, '2', NULL),
								(NULL, 'GUSTAVO', 'ISAAC', 'EFETIVADO', 2400.00, '3', NULL), (NULL, 'SANDRO', 'MARCELO', 'EFETIVADO', 2100.00, '4', NULL),
								(NULL, 'KELLY', 'DA SILVA', 'EFETIVADA', 2300.00, '5', NULL);
                                
SELECT * FROM FUNCIONARIO;

UPDATE FUNCIONARIO SET FK_CHEFE = '107' WHERE ID_FUNCIONARIO IN ('100', '102');
UPDATE FUNCIONARIO SET FK_CHEFE = '108' WHERE ID_FUNCIONARIO = '103';
UPDATE FUNCIONARIO SET FK_CHEFE = '109' WHERE ID_FUNCIONARIO IN ('104', '106');
UPDATE FUNCIONARIO SET FK_CHEFE = '110' WHERE ID_FUNCIONARIO = '101';
UPDATE FUNCIONARIO SET FK_CHEFE = '111' WHERE ID_FUNCIONARIO = '105';

/* selecionando tudo da tabela FUNCIONARIO */
SELECT * FROM FUNCIONARIO;

/* selecionando tudo da tabela DEPARTAMENTO */
SELECT * FROM DEPARTAMENTO;

/* selecionando tudo da tabela EMPRESA */
SELECT * FROM EMPRESA;

/* selecionando tudo da tabela DEPARTAMENTO_HAS_EMPRESA */
SELECT * FROM DEPARTAMENTO_HAS_EMPRESA;

/* Juntando a tabela EMPRESA e a tabela DEPARTAMENTO com a tabela associativa DEPARTAMENTO_HAS_EMPRESA */
SELECT E.NOME_EMPRESA, E.CEO_EMPRESA, D.NOME_DEPARTAMENTO, D.NUMERO_DEPARTAMENTO FROM
DEPARTAMENTO_HAS_EMPRESA DE JOIN DEPARTAMENTO D ON D.ID_DEPARTAMENTO = DE.FK_DEPARTAMENTO
JOIN EMPRESA E ON E.ID_EMPRESA = DE.FK_EMPRESA;

/* Juntando a tabela Funcionario com a propria tabela funcionario com seus respectivos chefes */
SELECT FUNCIONARIO.NOME_FUNCIONARIO AS NOME_FUNC, FUNCIONARIO.SOBRENOME_FUNCIONARIO AS SOBRENOME_FUNC, FUNCIONARIO.TITULO_FUNCIONARIO AS TITULO_FUNC, 
CHEFE.NOME_FUNCIONARIO AS NOME_CHEFE, CHEFE.SOBRENOME_FUNCIONARIO AS SOBRENOME_CHEFE, CHEFE.TITULO_FUNCIONARIO AS TITULO_CHEFE FROM
FUNCIONARIO AS FUNCIONARIO JOIN FUNCIONARIO AS CHEFE ON FUNCIONARIO.FK_CHEFE = CHEFE.ID_FUNCIONARIO;

/* Juntando a tabela Funcionario com a propria tabela funcionario com seus respectivos chefes, entretando dando prioridade a os funcionarios com chefe*/
SELECT FUNCIONARIO.NOME_FUNCIONARIO, FUNCIONARIO.SOBRENOME_FUNCIONARIO, FUNCIONARIO.TITULO_FUNCIONARIO, 
CHEFE.NOME_FUNCIONARIO, CHEFE.SOBRENOME_FUNCIONARIO, CHEFE.TITULO_FUNCIONARIO FROM
FUNCIONARIO AS CHEFE RIGHT JOIN FUNCIONARIO AS FUNCIONARIO ON FUNCIONARIO.FK_CHEFE = CHEFE.ID_FUNCIONARIO;

/* Juntando a tabela Funcionario com a propria tabela funcionario com seus respectivos chefes e seus respectivos departamentos*/
SELECT FUNCIONARIO.NOME_FUNCIONARIO AS NOME_FUNC, FUNCIONARIO.SOBRENOME_FUNCIONARIO AS SOBRENOME_FUNC, FUNCIONARIO.TITULO_FUNCIONARIO AS TITULO_FUNC, 
CHEFE.NOME_FUNCIONARIO AS NOME_CHEFE, CHEFE.SOBRENOME_FUNCIONARIO AS SOBRENOME_CHEFE, CHEFE.TITULO_FUNCIONARIO AS TITULO_CHEFE,
D.NOME_DEPARTAMENTO, D.NUMERO_DEPARTAMENTO FROM
FUNCIONARIO AS FUNCIONARIO JOIN FUNCIONARIO AS CHEFE ON FUNCIONARIO.FK_CHEFE = CHEFE.ID_FUNCIONARIO 
JOIN DEPARTAMENTO D ON D.ID_DEPARTAMENTO = FUNCIONARIO.FK_DEPARTAMENTO;

SELECT SUM(SALARIO) FROM FUNCIONARIO;

SELECT FK_CHEFE, SUM(SALARIO) FROM FUNCIONARIO group by FK_CHEFE;